import searchIcon from "../assets/features/search-icon.svg";
import selectIcon from "../assets/features/select-icon.svg";
import standOutIcon from "../assets/features/stand-out-icon.svg";

export const featuresData = [
  {
    id: 1,
    icon: searchIcon,
    label: "Search",
    description:
      "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.",
  },
  {
    id: 2,
    icon: selectIcon,
    label: "Select",
    description:
      "Choose from thousands of options generated by the slogan maker that fit your needs.",
  },
  {
    id: 3,
    icon: standOutIcon,
    label: "Stand out",
    description: "Congrats on your new slogan. It's time to win the world!",
  },
];
